name=input("What is your name human?")
print()
print()
age=int(input("How old are you (in years)?"))
print()
print()
height=float(input(("How tall are you (in meters)?")))
print()
print()
weight=float(input("How much do you weigh (in kilograms)?"))
print()
print()
total=(weight/height** 2)
print(f"{name} you are {age} years old and your bmi is  {total}")